### ISSUE TITLE
Can't create image and face detection is also not working 

### ISSUE THREAD

**Issue by ChanchalW** [Weijay/GoogleFaceDetection#1]
Hi, nice demo. It's actually not an issue. I am stuck and couldn't get a way around.
I am trying to work on live face detection like you implemented in this demo. But it's when I try to create the image it's crashing every time. Then I created an image and passed it to face detection. Its even not detecting any face. I think the major issue may be orientation but I am not able to solve this.  Bellow is my code : 
https://www.dropbox.com/s/sfb8hyqerawjl3p/untitled%20folder.zip?dl=0
Can you help?

**Comment by Willjay90** [comment]
I made some modification of ur code, just [check it out](https://drive.google.com/file/d/0B50nVFcsGrXgUnFHbzFOSndVYTQ/view?usp=sharing) ! Cheers :)
